name: compile2

on:
  workflow_dispatch:

jobs:     
  linux:
    name: Release manylinux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-path: ['cp36-cp36m', 'cp37-cp37m', 'cp38-cp38', 'cp39-cp39', 'cp310-cp310']
    container: quay.io/pypa/manylinux2014_x86_64:latest
    env:
      RUSTFLAGS: -C target-cpu=k8
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: yum install -y libffi libffi-devel openssl openssl-devel
      - run: /opt/python/${{ matrix.python-path }}/bin/python -m venv .venv
      - run: .venv/bin/pip install -U pip wheel
      - run: .venv/bin/pip install -U twine maturin
      - run: .venv/bin/maturin build --release --out dist --no-sdist -m Cargo.toml --compatibility manylinux2014 -i /opt/python/${{ matrix.python-path }}/bin/python

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist


  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [linux]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Publish to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_ACC }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing *